GET http://127.0.0.1:8080/productos

### GET ONLY PRODUCT
GET http://127.0.0.1:8080/productos/4

### POST
POST http://127.0.0.1:8080/productos
Content-Type: application/json



{
  "nombre": "testing otro producto",

  "precio": 1200.00
}


### DELETE
DELETE http://127.0.0.1:8080/productos/2